### ISSUE TITLE
Web App not working

### ISSUE THREAD

**Issue by nikabosedata** [arv-anshul/99acres-scrape#8]
Does not seem to load

**Comment by arv-anshul** [comment]
Yes @nikabosedata , I know 😞 and I am working on that.

**Comment by arv-anshul** [comment]
@nikabosedata I have fixed the issue and also checked it on my PC, it works fine.

> [!IMPORTANT]
> You have to submit curl command from website [99acres.com](https://www.99acres.com) to fetch data.

**❓ If you have any other query then ask them here.**
