### ISSUE TITLE
Streamlit Webapp is not working. Server Down.

### ISSUE THREAD

**Issue by abhishek-sanwal** [arv-anshul/99acres-scrape#9]
Webapp is not working on 23 Sep 2024 11 pm approx when I tried to opened it.

**Comment by arv-anshul** [comment]
Yep, it is expected and already specified in the **README**.

![image](https://github.com/user-attachments/assets/01421fa1-8099-4401-8616-daa27ecc013c)

**Comment by abhishek-sanwal** [comment]
Yes thanks for info.
